
package resgistroacademico;

/**
 *
 * @author kevin
 */
public class RegistrodeEstudianteGUI2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrodeEstudianteGUI2.class.getName());

    /**
     * Creates new form RegistrodeEstudianteGUI2
     */

    // Este es el constructor modificado para recibir el objeto
    // Constructor modificado para recibir el objeto Estudiantess
    public RegistrodeEstudianteGUI2(Estudiantess estudiante) {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana en pantalla
        
        // Mostrar todos los datos y el cálculo final si el estudiante no es nulo
        if(estudiante != null) {
            String reporte = "=== REPORTE ACADÉMICO DEL ESTUDIANTE ===\n\n" +
                             "Matrícula: " + estudiante.getMatricula() + "\n" +
                             "Nombre: " + estudiante.getNombre() + "\n" +
                             "Carrera: " + estudiante.getCarrera() + "\n\n" +
                             "--- CALIFICACIONES ---\n" +
                             "Prácticas: " + estudiante.getPracticas() + " / 40\n" +
                             "Parciales: " + estudiante.getParciales() + " / 20\n" +
                             "Asignaciones: " + estudiante.getAsignaciones() + " / 20\n" +
                             "Examen Final: " + estudiante.getExamenFinal() + " / 20\n\n" +
                             "===================================\n" +
                             "NOTA TOTAL: " + estudiante.calcularNotaTotal() + "\n" +
                             "ESTADO FINAL: " + estudiante.obtenerEstado() + "\n" +
                             "===================================";
            
            textAreadeResultados.setText(reporte);
            textAreadeResultados.setEditable(false); // Evita que el usuario escriba en el resultado
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreadeResultados = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreadeResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreadeResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea textAreadeResultados;
    // End of variables declaration//GEN-END:variables
}
