
package com.mycompany.tareapractica4.javaswing;

/**
 *
 * @author kevin
 */
public class Gui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gui.class.getName());

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        txtNum1 = new java.awt.TextField();
        txtNum2 = new java.awt.TextField();
        lblResultado = new java.awt.Label();
        btnSumar = new java.awt.Button();
        btnRestar = new java.awt.Button();
        btnMultiplicar = new java.awt.Button();
        btnDividir = new java.awt.Button();
        btnRaiz = new java.awt.Button();
        btnExponente = new java.awt.Button();
        btnFtoC = new java.awt.Button();
        btnCtoF = new java.awt.Button();
        btnLimpiar = new java.awt.Button();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResultado.setAlignment(java.awt.Label.CENTER);
        lblResultado.setText("el resultado se muestra aqui:");

        btnSumar.setLabel("sumar");
        btnSumar.addActionListener(this::btnSumarActionPerformed);

        btnRestar.setLabel("restar");
        btnRestar.addActionListener(this::btnRestarActionPerformed);

        btnMultiplicar.setLabel("Multiplicar");
        btnMultiplicar.addActionListener(this::btnMultiplicarActionPerformed);

        btnDividir.setLabel("dividir");
        btnDividir.addActionListener(this::btnDividirActionPerformed);

        btnRaiz.setLabel("raiz cuadrada");
        btnRaiz.addActionListener(this::btnRaizActionPerformed);

        btnExponente.setLabel("exponente");
        btnExponente.addActionListener(this::btnExponenteActionPerformed);

        btnFtoC.setLabel("de F a C");
        btnFtoC.addActionListener(this::btnFtoCActionPerformed);

        btnCtoF.setLabel("de C a F");
        btnCtoF.addActionListener(this::btnCtoFActionPerformed);

        btnLimpiar.setLabel("limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Calculadora ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnFtoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCtoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnExponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFtoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnExponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(btnCtoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        try {
    double n1 = Double.parseDouble(txtNum1.getText());
    double n2 = Double.parseDouble(txtNum2.getText());
    lblResultado.setText("Resultado: " + (n1 + n2));
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa números en ambos campos.");
}
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
      try {
    double n1 = Double.parseDouble(txtNum1.getText());
    double n2 = Double.parseDouble(txtNum2.getText());
    lblResultado.setText("Resultado: " + (n1 - n2));
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa números en ambos campos.");
}
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
       try {
    double n1 = Double.parseDouble(txtNum1.getText());
    double n2 = Double.parseDouble(txtNum2.getText());
    lblResultado.setText("Resultado: " + (n1 * n2));
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa números en ambos campos.");
}
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        try {
    double n1 = Double.parseDouble(txtNum1.getText());
    double n2 = Double.parseDouble(txtNum2.getText());
    
    if (n2 == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Error: No se puede dividir entre cero.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        lblResultado.setText("Resultado: " + (n1 / n2));
    }
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa números en ambos campos.");
}
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
       try {
    double n1 = Double.parseDouble(txtNum1.getText());
    
    if (n1 < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Error: No existe raíz cuadrada de números negativos.");
    } else {
        lblResultado.setText("Resultado: " + Math.sqrt(n1));
    }
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa el número en el primer campo.");
}
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponenteActionPerformed
       try {
    double base = Double.parseDouble(txtNum1.getText());
    double exponente = Double.parseDouble(txtNum2.getText());
    
    lblResultado.setText("Resultado: " + Math.pow(base, exponente));
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa la base arriba y el exponente abajo.");
}
    }//GEN-LAST:event_btnExponenteActionPerformed

    private void btnFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoCActionPerformed
       try {
    double fahrenheit = Double.parseDouble(txtNum1.getText());
    double celsius = (fahrenheit - 32) * (5.0 / 9.0);
    lblResultado.setText(fahrenheit + " °F  =  " + celsius + " °C");
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa la temperatura en el primer campo.");
}
    }//GEN-LAST:event_btnFtoCActionPerformed

    private void btnCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoFActionPerformed
      try {
    double celsius = Double.parseDouble(txtNum1.getText());
    double fahrenheit = (celsius * (9.0 / 5.0)) + 32;
    lblResultado.setText(celsius + " °C  =  " + fahrenheit + " °F");
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa la temperatura en el primer campo.");
}
    }//GEN-LAST:event_btnCtoFActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       txtNum1.setText("");
txtNum2.setText("");
lblResultado.setText("Resultado: --");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCtoF;
    private java.awt.Button btnDividir;
    private java.awt.Button btnExponente;
    private java.awt.Button btnFtoC;
    private java.awt.Button btnLimpiar;
    private java.awt.Button btnMultiplicar;
    private java.awt.Button btnRaiz;
    private java.awt.Button btnRestar;
    private java.awt.Button btnSumar;
    private java.awt.Label label1;
    private java.awt.Label lblResultado;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txtNum1;
    private java.awt.TextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
