
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author YMALAI DORANGEL LEONARDO RAMON
 */

public class InterfazParticipante extends javax.swing.JFrame {
    ProcesarDatos procesador = new ProcesarDatos();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazParticipante.class.getName());

    /**
     * Creates new form InterfazParticipante
     */
    public InterfazParticipante() {
        initComponents();
        //dimensiones fijas 
        panelPrincipal.setPreferredSize(new java.awt.Dimension(633, 355));
        //centralizar a la pantalla 
        setLocationRelativeTo(null);     
        
        configurarPlaceholder(txtMatricula, "Ej: 20251561");
        configurarPlaceholder(txtNombres, "Ej: Juan Pedro");        
        configurarPlaceholder(txtApellidos, "Ej: Pérez Rodríguez");
        configurarPlaceholder(txtCuatrimestres, "Ej: Primero");
        

    }
    
     //configuracion del placeholder
    private void configurarPlaceholder(JTextField campo, String placeholder) {
    campo.setText(placeholder);
    campo.setForeground(Color.GRAY);

    campo.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (campo.getText().equals(placeholder)) {
                campo.setText("");
                campo.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (campo.getText().isEmpty()) {
                campo.setText(placeholder);
                campo.setForeground(Color.GRAY);
            }
        }
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCuatrimestre = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        btnPresentar = new javax.swing.JButton();
        btnCapturar = new javax.swing.JButton();
        txtCuatrimestres = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Estudiantes");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(51, 0, 0));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Estudiantes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblCuatrimestre.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblCuatrimestre.setText("Cuatrimestre:");
        jPanel1.add(lblCuatrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblMatricula.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblMatricula.setText("Matrícula:");
        jPanel1.add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblNombres.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblNombres.setText("Nombres:");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblApellidos.setText("Apellidos:");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnPresentar.setText("PRESENTAR");
        btnPresentar.addActionListener(this::btnPresentarActionPerformed);
        jPanel1.add(btnPresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnCapturar.setText("CAPTURAR");
        btnCapturar.addActionListener(this::btnCapturarActionPerformed);
        jPanel1.add(btnCapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        txtCuatrimestres.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtCuatrimestres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.add(txtCuatrimestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 300, -1));

        txtMatricula.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, -1));

        txtNombres.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtNombres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, -1));

        txtApellidos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 300, -1));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed
           JOptionPane.showMessageDialog(this, procesador.presentarDatos());
    }//GEN-LAST:event_btnPresentarActionPerformed

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
            procesador.capturarDatos(
            txtMatricula.getText(),
            txtNombres.getText(),
            txtApellidos.getText(),
            txtCuatrimestres.getText()
        );
        JOptionPane.showMessageDialog(this, "¡Datos capturados!");
    }//GEN-LAST:event_btnCapturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazParticipante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnPresentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCuatrimestre;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCuatrimestres;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
