
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ymala
 */
public class RegistroAcademicoGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroAcademicoGUI.class.getName());

    /**
     * Creates new form RegistroAcademicoGUI
     */
    public RegistroAcademicoGUI() {
        initComponents();
        this.setSize(700, 500);
        this.pack();
                
        configurarPlaceholder(txtNombre, "Ej: Juan Pérez Rodríguez");
        configurarPlaceholder(txtMatricula, "Ej: 20251561");
        configurarPlaceholder(txtCarrera, "Ej: Desarrollo de Software");
        configurarPlaceholder(txtPracticas, "0 - 40");
        configurarPlaceholder(txtParciales, "0 - 20");
        configurarPlaceholder(txtAsignaciones, "0 - 20");
        configurarPlaceholder(txtExamenFinal, "0 - 20");
        
        //centrar el panel 
        getContentPane().setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        //gbc.insets = new Insets(10, 20, 10, 20);
        
        getContentPane().add(panelCuestionario, gbc);
        
        // Panel del formulario — columna 0
        gbc.gridx = 0;
        gbc.gridy = 0;
        getContentPane().add(panelCuestionario, gbc);

        // Panel de resultado — columna 1 (a la derecha)
        gbc.gridx = 1;
        gbc.gridy = 0;
        getContentPane().add(panelResultado, gbc); 
        
        // fondo del jframe        
        getContentPane().setBackground(new Color(173, 216, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuestionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPracticas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtParciales = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAsignaciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtExamenFinal = new javax.swing.JTextField();
        btnResultado = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblNotaFinal = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro academico");
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(50, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCuestionario.setBackground(new java.awt.Color(255, 255, 255));
        panelCuestionario.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Calculadora de calificaciones");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese los datos del estudiante y las calificaciones ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("para calcular el resultado final.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Datos del Estudiante");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre completo");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Matricula");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Carrera");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Calificaciones");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Total máximo: 100 puntos");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("(Prácticas: 40, Parciales: 20, Asignaciones: 20, Examen Final: 20)");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Practicas (0-40) ");

        txtPracticas.addActionListener(this::txtPracticasActionPerformed);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Parciales (0-20)");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Asignaciones (0-20)");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Examen final (0-20)");

        btnResultado.setText("CALCULAR RESULTADO");
        btnResultado.setAutoscrolls(true);
        btnResultado.addActionListener(this::btnResultadoActionPerformed);

        javax.swing.GroupLayout panelCuestionarioLayout = new javax.swing.GroupLayout(panelCuestionario);
        panelCuestionario.setLayout(panelCuestionarioLayout);
        panelCuestionarioLayout.setHorizontalGroup(
            panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuestionarioLayout.createSequentialGroup()
                .addGap(42, 45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
            .addGroup(panelCuestionarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(panelCuestionarioLayout.createSequentialGroup()
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(panelCuestionarioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(panelCuestionarioLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnResultado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuestionarioLayout.setVerticalGroup(
            panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuestionarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExamenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResultado)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panelCuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 540));

        panelResultado.setBackground(new java.awt.Color(153, 255, 255));

        lblResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 0, 0));

        lblNotaFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNotaFinal.setForeground(new java.awt.Color(0, 0, 0));
        lblNotaFinal.setText("Nota Final: ");

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMensaje1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNotaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblResultado)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNotaFinal)
                .addGap(12, 12, 12)
                .addComponent(lblMensaje)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje1)
                .addContainerGap())
        );

        getContentPane().add(panelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 240, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticasActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        // ── Validar nombre ──────────────────────────────────────────
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty() || nombre.equals("Ej: Juan Pérez Rodríguez") || !nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this,
                "Ingresa un nombre válido (solo letras y espacios).",
                "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ── Validar matrícula ───────────────────────────────────────
        String matricula = txtMatricula.getText().trim();
        if (matricula.isEmpty() || matricula.equals("Ej: 20251101") || !matricula.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this,
                "La matrícula debe tener exactamente 8 dígitos.",
                "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int matriculaNum = Integer.parseInt(matricula);
        if (matriculaNum < 20200001 || matriculaNum > 20262999) {
            JOptionPane.showMessageDialog(this,
                "La matrícula debe estar entre 20200001 y 20262999.",
                "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ── Validar carrera ─────────────────────────────────────────
        String carrera = txtCarrera.getText().trim();
        if (carrera.isEmpty() || carrera.equals("Ej: Desarrollo de Software") || !carrera.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this,
                "Ingresa una carrera válida (solo letras y espacios).",
                "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ── Validar calificaciones ──────────────────────────────────
        int practicas, parciales, asignaciones, examenFinal;
        try {
            String txtP = txtPracticas.getText().trim();
            if (txtP.equals("0 - 40")) throw new NumberFormatException();
            practicas = Integer.parseInt(txtP);
            if (practicas < 0 || practicas > 40) throw new NumberFormatException();

            String txtPar = txtParciales.getText().trim();
            if (txtPar.equals("0 - 20")) throw new NumberFormatException();
            parciales = Integer.parseInt(txtPar);
            if (parciales < 0 || parciales > 20) throw new NumberFormatException();

            String txtA = txtAsignaciones.getText().trim();
            if (txtA.equals("0 - 20")) throw new NumberFormatException();
            asignaciones = Integer.parseInt(txtA);
            if (asignaciones < 0 || asignaciones > 20) throw new NumberFormatException();

            String txtE = txtExamenFinal.getText().trim();
            if (txtE.equals("0 - 20")) throw new NumberFormatException();
            examenFinal = Integer.parseInt(txtE);
            if (examenFinal < 0 || examenFinal > 20) throw new NumberFormatException();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Verifica las calificaciones:\n" +
                "  • Prácticas: 0 - 40\n" +
                "  • Parciales: 0 - 20\n" +
                "  • Asignaciones: 0 - 20\n" +
                "  • Examen Final: 0 - 20",
                "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // ── Crear estudiante y calcular ─────────────────────────────
        Estudiante estudiante = new Estudiante(nombre, matricula, carrera,
            practicas, parciales, asignaciones, examenFinal);

        int nota = estudiante.calcularNotaFinal();

        // ── Actualizar panel de resultado ───────────────────────────
        if (estudiante.estaAprobado()) {
            lblResultado.setText("Aprobado");
            lblNotaFinal.setText("Nota Final:   " + nota);
            lblMensaje.setText("¡Felicidades!");
            lblMensaje1.setText("Has aprobado el curso.");
        } else {
            lblResultado.setText("Reprobado");
            lblNotaFinal.setText("Nota Final:   " + nota);
            lblMensaje.setText("");
            lblMensaje1.setText("Necesitas esforzarte.");
        }

        // ── Limpiar formulario con placeholders ────────────────────────
        txtNombre.setText("Ej: Juan Pérez Rodríguez");
        txtNombre.setForeground(Color.GRAY);

        txtMatricula.setText("Ej: 20251561");
        txtMatricula.setForeground(Color.GRAY);

        txtCarrera.setText("Ej: Desarrollo de Software");
        txtCarrera.setForeground(Color.GRAY);

        txtPracticas.setText("0 - 40");
        txtPracticas.setForeground(Color.GRAY);

        txtParciales.setText("0 - 20");
        txtParciales.setForeground(Color.GRAY);

        txtAsignaciones.setText("0 - 20");
        txtAsignaciones.setForeground(Color.GRAY);

        txtExamenFinal.setText("0 - 20");
        txtExamenFinal.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnResultadoActionPerformed
    
    //configuracion del placeholder
    private void configurarPlaceholder(JTextField campo, String placeholder) {
    campo.setText(placeholder);
    campo.setForeground(Color.GRAY);

    campo.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (campo.getText().equals(placeholder)) {
                campo.setText("");
                campo.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (campo.getText().isEmpty()) {
                campo.setText(placeholder);
                campo.setForeground(Color.GRAY);
            }
        }
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroAcademicoGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblNotaFinal;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panelCuestionario;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamenFinal;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPracticas;
    // End of variables declaration//GEN-END:variables
}
